defmodule LittleGrapeWeb.UserProfileHTML do
  use LittleGrapeWeb, :html

  embed_templates "user_profile_html/*"

  def translate_option(option, :gender), do: translate_gender(option)
  def translate_option(option, :country), do: translate_country(option)
  def translate_option(option, :body_type), do: translate_body_type(option)
  def translate_option(option, :eye_color), do: translate_eye_color(option)
  def translate_option(option, :hair_color), do: translate_hair_color(option)
  def translate_option(option, :looking_for), do: translate_looking_for(option)
  def translate_option(option, :smoking), do: translate_smoking(option)
  def translate_option(option, :drinking), do: translate_drinking(option)
  def translate_option(option, :wants_children), do: translate_wants_children(option)
  def translate_option(option, :education), do: translate_education(option)
  def translate_option(option, :religion), do: translate_religion(option)
  def translate_option(option, :language), do: translate_language(option)
  def translate_option(option, :interest), do: translate_interest(option)

  defp translate_gender("male"), do: gettext("Male")
  defp translate_gender("female"), do: gettext("Female")
  defp translate_gender("other"), do: gettext("Other")

  defp translate_country("AL"), do: gettext("Albania")
  defp translate_country("XK"), do: gettext("Kosovo")
  defp translate_country("MK"), do: gettext("North Macedonia")
  defp translate_country("ME"), do: gettext("Montenegro")
  defp translate_country("RS"), do: gettext("Serbia")
  defp translate_country("BA"), do: gettext("Bosnia and Herzegovina")
  defp translate_country("HR"), do: gettext("Croatia")
  defp translate_country("SI"), do: gettext("Slovenia")
  defp translate_country("GR"), do: gettext("Greece")
  defp translate_country("IT"), do: gettext("Italy")
  defp translate_country("AT"), do: gettext("Austria")
  defp translate_country("DE"), do: gettext("Germany")
  defp translate_country("CH"), do: gettext("Switzerland")
  defp translate_country("BE"), do: gettext("Belgium")
  defp translate_country("NL"), do: gettext("Netherlands")
  defp translate_country("FR"), do: gettext("France")
  defp translate_country("GB"), do: gettext("United Kingdom")
  defp translate_country("US"), do: gettext("United States")
  defp translate_country("CA"), do: gettext("Canada")
  defp translate_country("AU"), do: gettext("Australia")
  defp translate_country("SE"), do: gettext("Sweden")
  defp translate_country("NO"), do: gettext("Norway")
  defp translate_country("DK"), do: gettext("Denmark")
  defp translate_country("FI"), do: gettext("Finland")
  defp translate_country("ES"), do: gettext("Spain")
  defp translate_country("PT"), do: gettext("Portugal")
  defp translate_country("TR"), do: gettext("Turkey")
  defp translate_country("CY"), do: gettext("Cyprus")
  defp translate_country("MT"), do: gettext("Malta")
  defp translate_country("other"), do: gettext("Other")

  defp translate_body_type("slim"), do: gettext("Slim")
  defp translate_body_type("athletic"), do: gettext("Athletic")
  defp translate_body_type("average"), do: gettext("Average")
  defp translate_body_type("curvy"), do: gettext("Curvy")
  defp translate_body_type("muscular"), do: gettext("Muscular")
  defp translate_body_type("plus_size"), do: gettext("Plus Size")

  defp translate_eye_color("brown"), do: gettext("Brown")
  defp translate_eye_color("blue"), do: gettext("Blue")
  defp translate_eye_color("green"), do: gettext("Green")
  defp translate_eye_color("hazel"), do: gettext("Hazel")
  defp translate_eye_color("gray"), do: gettext("Gray")
  defp translate_eye_color("black"), do: gettext("Black")

  defp translate_hair_color("black"), do: gettext("Black")
  defp translate_hair_color("brown"), do: gettext("Brown")
  defp translate_hair_color("blonde"), do: gettext("Blonde")
  defp translate_hair_color("red"), do: gettext("Red")
  defp translate_hair_color("gray"), do: gettext("Gray")
  defp translate_hair_color("white"), do: gettext("White")
  defp translate_hair_color("other"), do: gettext("Other")

  defp translate_looking_for("friendship"), do: gettext("Friendship")
  defp translate_looking_for("dating"), do: gettext("Dating")
  defp translate_looking_for("relationship"), do: gettext("Relationship")
  defp translate_looking_for("marriage"), do: gettext("Marriage")
  defp translate_looking_for("not_sure"), do: gettext("Not Sure")

  # Smoking options
  defp translate_smoking("non_smoker"), do: gettext("Non-smoker")
  defp translate_smoking("occasional"), do: gettext("Occasional smoker")
  defp translate_smoking("regular"), do: gettext("Regular smoker")

  # Drinking options
  defp translate_drinking("non_drinker"), do: gettext("Non-drinker")
  defp translate_drinking("social"), do: gettext("Social drinker")
  defp translate_drinking("regular"), do: gettext("Regular drinker")

  # Wants children options
  defp translate_wants_children("yes"), do: gettext("Yes")
  defp translate_wants_children("no"), do: gettext("No")
  defp translate_wants_children("maybe"), do: gettext("Maybe")
  defp translate_wants_children("have_and_want_more"), do: gettext("Have children, want more")

  # Education options
  defp translate_education("high_school"), do: gettext("High School")
  defp translate_education("some_college"), do: gettext("Some College")
  defp translate_education("bachelors"), do: gettext("Bachelor's Degree")
  defp translate_education("masters"), do: gettext("Master's Degree")
  defp translate_education("doctorate"), do: gettext("Doctorate")
  defp translate_education("other"), do: gettext("Other")

  # Religion options
  defp translate_religion("muslim"), do: gettext("Muslim")
  defp translate_religion("orthodox"), do: gettext("Orthodox Christian")
  defp translate_religion("catholic"), do: gettext("Catholic")
  defp translate_religion("atheist"), do: gettext("Atheist")
  defp translate_religion("other"), do: gettext("Other")
  defp translate_religion("prefer_not_to_say"), do: gettext("Prefer not to say")

  # Language options
  defp translate_language("sq"), do: gettext("Albanian")
  defp translate_language("en"), do: gettext("English")
  defp translate_language("it"), do: gettext("Italian")
  defp translate_language("de"), do: gettext("German")
  defp translate_language("fr"), do: gettext("French")
  defp translate_language("sr"), do: gettext("Serbian")
  defp translate_language("mk"), do: gettext("Macedonian")
  defp translate_language("tr"), do: gettext("Turkish")
  defp translate_language("other"), do: gettext("Other")

  # Interest options
  defp translate_interest("sports"), do: gettext("Sports")
  defp translate_interest("music"), do: gettext("Music")
  defp translate_interest("travel"), do: gettext("Travel")
  defp translate_interest("reading"), do: gettext("Reading")
  defp translate_interest("cooking"), do: gettext("Cooking")
  defp translate_interest("movies"), do: gettext("Movies")
  defp translate_interest("fitness"), do: gettext("Fitness")
  defp translate_interest("art"), do: gettext("Art")
  defp translate_interest("nature"), do: gettext("Nature")
  defp translate_interest("technology"), do: gettext("Technology")
  defp translate_interest("gaming"), do: gettext("Gaming")
  defp translate_interest("photography"), do: gettext("Photography")
  defp translate_interest("dancing"), do: gettext("Dancing")
  defp translate_interest("fashion"), do: gettext("Fashion")
end
